revoke execute on function public.adjust_credits(uuid, integer, text, uuid) from public;
revoke execute on function public.adjust_credits(uuid, integer, text, uuid) from anon;
revoke execute on function public.adjust_credits(uuid, integer, text, uuid) from authenticated;
grant execute on function public.adjust_credits(uuid, integer, text, uuid) to service_role;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.handle_new_user() from anon;
revoke execute on function public.handle_new_user() from authenticated;
revoke execute on function public.set_updated_at() from public;
revoke execute on function public.set_updated_at() from anon;
revoke execute on function public.set_updated_at() from authenticated;
alter function public.set_updated_at() set search_path = public, pg_temp;
alter function public.handle_new_user() set search_path = public, pg_temp;
alter function public.adjust_credits(uuid, integer, text, uuid) set search_path = public, pg_temp;
